AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Consumer side of CFN Artifact Distribution.

Globals:
    Function:
        Timeout: 3

Parameters:

Resources:

Outputs:
